<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Attendance Report - {{ $selectedDivision->division_name }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h2 { margin: 0; color: #333; }
        .info { margin-bottom: 15px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; font-weight: bold; }
        .stats { margin-top: 20px; padding: 10px; background-color: #f9f9f9; border-radius: 5px; }
        .stats table { width: 50%; }
        .present { color: #28a745; font-weight: bold; }
        .absent { color: #dc3545; font-weight: bold; }
        .late { color: #ffc107; font-weight: bold; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Attendance Report</h2>
        <p>{{ $selectedDivision->division_name }}</p>
    </div>

    <div class="info">
        <strong>Report Period:</strong> {{ \Carbon\Carbon::parse($startDate)->format('d M Y') }} to {{ \Carbon\Carbon::parse($endDate)->format('d M Y') }}<br>
        <strong>Generated On:</strong> {{ \Carbon\Carbon::now()->format('d M Y h:i A') }}
    </div>

    <div class="stats">
        <h3>Summary Statistics</h3>
        <table>
            <tr>
                <td><strong>Total Records:</strong></td>
                <td>{{ $totalRecords }}</td>
            </tr>
            <tr>
                <td><strong>Present:</strong></td>
                <td class="present">{{ $presentCount }} ({{ $totalRecords > 0 ? round($presentCount/$totalRecords*100, 2) : 0 }}%)</td>
            </tr>
            <tr>
                <td><strong>Absent:</strong></td>
                <td class="absent">{{ $absentCount }} ({{ $totalRecords > 0 ? round($absentCount/$totalRecords*100, 2) : 0 }}%)</td>
            </tr>
            <tr>
                <td><strong>Late:</strong></td>
                <td class="late">{{ $lateCount }} ({{ $totalRecords > 0 ? round($lateCount/$totalRecords*100, 2) : 0 }}%)</td>
            </tr>
            <tr>
                <td><strong>Overall Attendance:</strong></td>
                <td><strong>{{ $attendancePercentage }}%</strong></td>
            </tr>
        </table>
    </div>

    <h3>Detailed Attendance Records</h3>
    <table>
        <thead>
            <tr>
                <th>S.No</th>
                <th>Date</th>
                <th>Student</th>
                <th>Roll No</th>
                <th>Subject</th>
                <th>Status</th>
                <th>Remarks</th>
            </tr>
        </thead>
        <tbody>
            @foreach($attendances as $index => $attendance)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $attendance->date->format('d M Y') }}</td>
                <td>{{ $attendance->student->full_name ?? 'N/A' }}</td>
                <td>{{ $attendance->student->roll_number ?? 'N/A' }}</td>
                <td>{{ $attendance->timetable->subject->name ?? 'N/A' }}</td>
                <td class="{{ $attendance->status }}">{{ ucfirst($attendance->status) }}</td>
                <td>{{ $attendance->remarks ?? '-' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by School ERP System | Page 1 of 1</p>
    </div>
</body>
</html>
